import type { Agent, Task, Crew, SystemStats, ActivityLog } from '../types'

// Mock Agents
export const mockAgents: Agent[] = [
  {
    id: 'agent_001',
    name: 'ContentOrchestrator',
    role: '内容编排者',
    status: 'running',
    last_activity: new Date().toISOString(),
    metrics: { total_executions: 156, success_rate: 0.95, avg_duration_ms: 45000, tokens_used: 125000 },
    current_task: '编排小红书内容生产',
    progress: 60,
  },
  {
    id: 'agent_002',
    name: 'Researcher',
    role: '热点研究员',
    status: 'idle',
    last_activity: new Date(Date.now() - 300000).toISOString(),
    metrics: { total_executions: 89, success_rate: 0.97, avg_duration_ms: 25000, tokens_used: 78000 },
  },
  {
    id: 'agent_003',
    name: 'Marketer',
    role: '营销策划师',
    status: 'waiting',
    last_activity: new Date(Date.now() - 120000).toISOString(),
    metrics: { total_executions: 67, success_rate: 0.96, avg_duration_ms: 18000, tokens_used: 56000 },
    current_task: '等待研究报告',
  },
  {
    id: 'agent_004',
    name: 'Copywriter',
    role: '文案创作者',
    status: 'idle',
    last_activity: new Date(Date.now() - 600000).toISOString(),
    metrics: { total_executions: 134, success_rate: 0.93, avg_duration_ms: 35000, tokens_used: 198000 },
  },
  {
    id: 'agent_005',
    name: 'Designer',
    role: '视觉设计师',
    status: 'idle',
    last_activity: new Date(Date.now() - 900000).toISOString(),
    metrics: { total_executions: 45, success_rate: 0.91, avg_duration_ms: 42000, tokens_used: 34000 },
  },
  {
    id: 'agent_006',
    name: 'ContentReviewer',
    role: '内容审核员',
    status: 'idle',
    last_activity: new Date(Date.now() - 180000).toISOString(),
    metrics: { total_executions: 156, success_rate: 0.98, avg_duration_ms: 12000, tokens_used: 45000 },
  },
  {
    id: 'agent_007',
    name: 'PlatformAdapter',
    role: '平台适配师',
    status: 'running',
    last_activity: new Date().toISOString(),
    metrics: { total_executions: 89, success_rate: 0.97, avg_duration_ms: 25000, tokens_used: 67000 },
    current_task: '适配微博格式',
    progress: 40,
  },
  {
    id: 'agent_008',
    name: 'PlatformPublisher',
    role: '平台发布员',
    status: 'idle',
    last_activity: new Date(Date.now() - 3600000).toISOString(),
    metrics: { total_executions: 78, success_rate: 0.92, avg_duration_ms: 18000 },
  },
  {
    id: 'agent_009',
    name: 'DataAnalyst',
    role: '数据分析师',
    status: 'idle',
    last_activity: new Date(Date.now() - 7200000).toISOString(),
    metrics: { total_executions: 23, success_rate: 1.0, avg_duration_ms: 35000, tokens_used: 28000 },
  },
]

// Mock Tasks
export const mockTasks: Task[] = [
  {
    id: 'task_001',
    crew_id: 'crew_001',
    agent_id: 'agent_001',
    title: '生成小红书爆款内容',
    description: '主题: AI产品经理认知, 平台: 小红书',
    status: 'running',
    priority: 'high',
    created_at: new Date(Date.now() - 600000).toISOString(),
    started_at: new Date(Date.now() - 300000).toISOString(),
    input: { topic: 'AI产品经理认知', platform: 'xiaohongshu', style: 'professional' },
    retry_count: 0,
  },
  {
    id: 'task_002',
    crew_id: 'crew_001',
    agent_id: 'agent_007',
    title: '适配微博内容格式',
    description: '将已审核内容适配为微博格式',
    status: 'running',
    priority: 'medium',
    created_at: new Date(Date.now() - 400000).toISOString(),
    started_at: new Date(Date.now() - 120000).toISOString(),
    input: { platform: 'weibo', content_id: 'draft_001' },
    retry_count: 0,
  },
  {
    id: 'task_003',
    crew_id: 'crew_002',
    title: '知乎文章发布',
    description: '发布已适配的知乎文章',
    status: 'pending',
    priority: 'medium',
    created_at: new Date(Date.now() - 200000).toISOString(),
    input: { platform: 'zhihu', content_id: 'adapted_002' },
    retry_count: 0,
  },
  {
    id: 'task_004',
    crew_id: 'crew_001',
    title: '数据分析报告',
    description: '生成本周内容数据分析报告',
    status: 'completed',
    priority: 'low',
    created_at: new Date(Date.now() - 86400000).toISOString(),
    started_at: new Date(Date.now() - 86000000).toISOString(),
    completed_at: new Date(Date.now() - 85000000).toISOString(),
    input: { time_range: 'weekly' },
    output: { summary: '本周发布12篇内容，总浏览量5.2万' },
    retry_count: 0,
  },
  {
    id: 'task_005',
    crew_id: 'crew_002',
    title: '抖音脚本创作',
    description: '创作抖音短视频脚本',
    status: 'failed',
    priority: 'high',
    created_at: new Date(Date.now() - 172800000).toISOString(),
    started_at: new Date(Date.now() - 172000000).toISOString(),
    input: { topic: '程序员日常', platform: 'douyin' },
    error: 'LLM API 超时',
    retry_count: 2,
  },
]

// Mock Crews
export const mockCrews: Crew[] = [
  {
    id: 'crew_001',
    name: 'ContentCrew',
    status: 'running',
    agents: ['agent_001', 'agent_002', 'agent_003', 'agent_004', 'agent_005', 'agent_006', 'agent_007'],
    current_step: 3,
    total_steps: 5,
    started_at: new Date(Date.now() - 600000).toISOString(),
  },
  {
    id: 'crew_002',
    name: 'PublishCrew',
    status: 'idle',
    agents: ['agent_007', 'agent_008'],
    current_step: 0,
    total_steps: 2,
  },
  {
    id: 'crew_003',
    name: 'AnalyticsCrew',
    status: 'completed',
    agents: ['agent_009'],
    current_step: 1,
    total_steps: 1,
    started_at: new Date(Date.now() - 86400000).toISOString(),
    completed_at: new Date(Date.now() - 85000000).toISOString(),
  },
]

// Mock Stats
export const mockStats: SystemStats = {
  active_crews: 1,
  active_agents: 2,
  pending_tasks: 3,
  completed_today: 8,
  total_tokens_today: 245000,
  api_calls_today: 67,
}

// Mock Activity Logs
export const mockLogs: ActivityLog[] = [
  { id: '1', timestamp: new Date().toISOString(), level: 'info', agent_name: 'ContentOrchestrator', message: '开始编排小红书内容生产任务' },
  { id: '2', timestamp: new Date(Date.now() - 5000).toISOString(), level: 'success', agent_name: 'Researcher', message: '热点研究完成，发现3个高潜力话题' },
  { id: '3', timestamp: new Date(Date.now() - 15000).toISOString(), level: 'info', agent_name: 'Marketer', message: '正在制定内容策略...' },
  { id: '4', timestamp: new Date(Date.now() - 30000).toISOString(), level: 'warning', agent_name: 'PlatformAdapter', message: '微博API限流，等待30秒后重试' },
  { id: '5', timestamp: new Date(Date.now() - 60000).toISOString(), level: 'success', agent_name: 'ContentReviewer', message: '内容审核通过，质量评分: 92/100' },
  { id: '6', timestamp: new Date(Date.now() - 120000).toISOString(), level: 'error', agent_name: 'Designer', message: 'DALL-E API 调用失败，使用备选方案' },
  { id: '7', timestamp: new Date(Date.now() - 180000).toISOString(), level: 'info', agent_name: 'Copywriter', message: '文案创作完成，生成3个标题变体' },
  { id: '8', timestamp: new Date(Date.now() - 240000).toISOString(), level: 'success', agent_name: 'PlatformPublisher', message: '小红书发布成功 - 笔记ID: xhs_12345' },
]
