-- Crew Media Ops Database Schema
-- PostgreSQL 15+

-- Enable extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pg_trgm";  -- For text search

-- ============================================
-- Enum Types
-- ============================================

CREATE TYPE content_status AS ENUM (
    'draft', 'in_review', 'approved', 'rejected', 'scheduled', 'published'
);

CREATE TYPE task_status AS ENUM (
    'pending', 'running', 'completed', 'failed', 'cancelled'
);

CREATE TYPE task_type AS ENUM (
    'research', 'generate', 'review', 'publish', 'analyze'
);

CREATE TYPE agent_status AS ENUM (
    'idle', 'running', 'error', 'disabled'
);

-- ============================================
-- Core Tables
-- ============================================

-- Content Briefs (from topic research)
CREATE TABLE content_briefs (
    id VARCHAR(50) PRIMARY KEY DEFAULT 'brief-' || replace(gen_random_uuid()::text, '-', '')::varchar(12),
    topic VARCHAR(200) NOT NULL,
    sub_topics JSONB DEFAULT NULL,
    keywords JSONB NOT NULL DEFAULT '[]',
    target_audience JSONB NOT NULL DEFAULT '{}',
    trending_topics JSONB NOT NULL DEFAULT '{}',
    content_angle TEXT NOT NULL,
    tone VARCHAR(20) NOT NULL DEFAULT 'professional',
    suggested_content_type VARCHAR(20) NOT NULL,
    primary_platform VARCHAR(20) NOT NULL,
    secondary_platforms JSONB NOT NULL DEFAULT '[]',
    key_points JSONB NOT NULL DEFAULT '[]',
    call_to_action TEXT DEFAULT '',
    hashtags JSONB NOT NULL DEFAULT '[]',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_content_briefs_topic ON content_briefs(topic);
CREATE INDEX idx_content_briefs_created ON content_briefs(created_at DESC);

-- Content Drafts (generated by content crew)
CREATE TABLE content_drafts (
    id VARCHAR(50) PRIMARY KEY DEFAULT 'draft-' || replace(gen_random_uuid()::text, '-', '')::varchar(12),
    brief_id VARCHAR(50) NOT NULL REFERENCES content_briefs(id) ON DELETE CASCADE,
    status content_status NOT NULL DEFAULT 'draft',
    version INTEGER NOT NULL DEFAULT 1,

    -- Content
    topic VARCHAR(200) NOT NULL,
    content_type VARCHAR(20) NOT NULL,
    platforms JSONB NOT NULL DEFAULT '[]',
    platform_content JSONB NOT NULL DEFAULT '[]',  -- List of platform-specific content

    -- Branding
    brand_voice VARCHAR(100) DEFAULT '',
    tone VARCHAR(20) NOT NULL DEFAULT 'professional',

    -- Review
    reviews JSONB NOT NULL DEFAULT '[]',  -- List of review feedbacks
    current_score JSONB DEFAULT NULL,  -- Quality score

    -- Tags
    tags JSONB NOT NULL DEFAULT '[]',
    category VARCHAR(50) DEFAULT '',

    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_content_drafts_status ON content_drafts(status);
CREATE INDEX idx_content_drafts_topic ON content_drafts(topic);
CREATE INDEX idx_content_drafts_brief ON content_drafts(brief_id);

-- Publish Logs
CREATE TABLE publish_logs (
    id VARCHAR(50) PRIMARY KEY DEFAULT 'pub-' || replace(gen_random_uuid()::text, '-', '')::varchar(12),
    draft_id VARCHAR(50) REFERENCES content_drafts(id) ON DELETE SET NULL,
    content_id VARCHAR(50) DEFAULT NULL,  -- Reference to published content

    -- Platform info
    platform VARCHAR(50) NOT NULL,
    account_id VARCHAR(50) DEFAULT NULL,  -- Platform account

    -- Status
    status VARCHAR(20) NOT NULL DEFAULT 'pending',  -- pending, success, failed
    published_url VARCHAR(500) DEFAULT NULL,
    published_at TIMESTAMPTZ DEFAULT NULL,

    -- Error handling
    error_message TEXT DEFAULT NULL,
    retry_count INTEGER DEFAULT 0,

    -- Scheduled
    scheduled_at TIMESTAMPTZ DEFAULT NULL,

    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_publish_logs_draft ON publish_logs(draft_id);
CREATE INDEX idx_publish_logs_platform ON publish_logs(platform);
CREATE INDEX idx_publish_logs_status ON publish_logs(status);
CREATE INDEX idx_publish_logs_scheduled ON publish_logs(scheduled_at) WHERE status = 'pending';

-- Analytics
CREATE TABLE analytics (
    id VARCHAR(50) PRIMARY KEY DEFAULT 'ana-' || replace(gen_random_uuid()::text, '-', '')::varchar(12),
    draft_id VARCHAR(50) REFERENCES content_drafts(id) ON DELETE SET NULL,
    publish_log_id VARCHAR(50) REFERENCES publish_logs(id) ON DELETE SET NULL,
    content_id VARCHAR(50) DEFAULT NULL,

    -- Platform
    platform VARCHAR(50) NOT NULL,
    platform_content_id VARCHAR(100) DEFAULT NULL,  -- ID on the platform

    -- Metrics
    views INTEGER DEFAULT 0,
    likes INTEGER DEFAULT 0,
    comments INTEGER DEFAULT 0,
    shares INTEGER DEFAULT 0,
    saves INTEGER DEFAULT 0,
    engagement_rate FLOAT DEFAULT 0.0,

    -- Extended metrics (platform-specific)
    extra_metrics JSONB DEFAULT '{}',

    -- Tracking
    collected_at TIMESTAMPTZ DEFAULT NOW(),
    period_start TIMESTAMPTZ DEFAULT NULL,
    period_end TIMESTAMPTZ DEFAULT NULL
);

CREATE INDEX idx_analytics_draft ON analytics(draft_id);
CREATE INDEX idx_analytics_platform ON analytics(platform);
CREATE INDEX idx_analytics_collected ON analytics(collected_at DESC);

-- ============================================
-- Task Management
-- ============================================

CREATE TABLE tasks (
    id VARCHAR(50) PRIMARY KEY DEFAULT 'task-' || to_char(NOW(), 'YYYYMMDDHH24MISS') || '-' || floor(random() * 1000)::int,
    type task_type NOT NULL,
    status task_status NOT NULL DEFAULT 'pending',

    -- Task info
    title VARCHAR(200) NOT NULL,
    description TEXT DEFAULT NULL,

    -- Input/Output
    input_data JSONB NOT NULL DEFAULT '{}',
    output_data JSONB DEFAULT NULL,

    -- Tracking
    progress INTEGER DEFAULT 0,
    error TEXT DEFAULT NULL,

    -- Agent assignment
    agent_name VARCHAR(50) DEFAULT NULL,
    crew_name VARCHAR(50) DEFAULT NULL,

    -- Timing
    started_at TIMESTAMPTZ DEFAULT NULL,
    completed_at TIMESTAMPTZ DEFAULT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_tasks_status ON tasks(status);
CREATE INDEX idx_tasks_type ON tasks(type);
CREATE INDEX idx_tasks_created ON tasks(created_at DESC);
CREATE INDEX idx_tasks_agent ON tasks(agent_name);

-- ============================================
-- Agent Registry
-- ============================================

CREATE TABLE agents (
    id VARCHAR(50) PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    role VARCHAR(200) NOT NULL,
    status agent_status NOT NULL DEFAULT 'idle',

    -- Capabilities
    tools JSONB NOT NULL DEFAULT '[]',
    llm_model VARCHAR(100) DEFAULT NULL,

    -- Statistics
    total_executions INTEGER DEFAULT 0,
    successful_executions INTEGER DEFAULT 0,
    failed_executions INTEGER DEFAULT 0,
    avg_execution_time FLOAT DEFAULT 0.0,

    -- Last execution
    last_execution_at TIMESTAMPTZ DEFAULT NULL,
    last_error TEXT DEFAULT NULL,

    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================
-- Recommendations
-- ============================================

CREATE TABLE recommendations (
    id SERIAL PRIMARY KEY,
    content_id VARCHAR(50) REFERENCES content_drafts(id) ON DELETE CASCADE,

    -- Recommendation
    recommendation_type VARCHAR(50) NOT NULL,  -- improvement, viral_pattern, timing, etc.
    content TEXT NOT NULL,
    priority INTEGER DEFAULT 0,  -- Higher = more important

    -- Source
    source_agent VARCHAR(50) DEFAULT NULL,
    confidence FLOAT DEFAULT 0.0,

    -- Status
    applied BOOLEAN DEFAULT FALSE,
    applied_at TIMESTAMPTZ DEFAULT NULL,

    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_recommendations_content ON recommendations(content_id);
CREATE INDEX idx_recommendations_type ON recommendations(recommendation_type);
CREATE INDEX idx_recommendations_priority ON recommendations(priority DESC);

-- ============================================
-- Webhook Events
-- ============================================

CREATE TABLE webhook_events (
    id SERIAL PRIMARY KEY,
    event_type VARCHAR(100) NOT NULL,
    source VARCHAR(100) DEFAULT NULL,

    -- Payload
    payload JSONB NOT NULL DEFAULT '{}',

    -- Processing
    processed BOOLEAN DEFAULT FALSE,
    processed_at TIMESTAMPTZ DEFAULT NULL,
    response TEXT DEFAULT NULL,

    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_webhook_events_type ON webhook_events(event_type);
CREATE INDEX idx_webhook_events_processed ON webhook_events(processed);
CREATE INDEX idx_webhook_events_created ON webhook_events(created_at DESC);

-- ============================================
-- Audit Log
-- ============================================

CREATE TABLE audit_logs (
    id SERIAL PRIMARY KEY,
    action VARCHAR(100) NOT NULL,
    entity_type VARCHAR(50) NOT NULL,
    entity_id VARCHAR(50) DEFAULT NULL,

    -- Details
    old_values JSONB DEFAULT NULL,
    new_values JSONB DEFAULT NULL,

    -- Actor
    user_id VARCHAR(50) DEFAULT NULL,
    ip_address VARCHAR(50) DEFAULT NULL,
    user_agent VARCHAR(500) DEFAULT NULL,

    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_audit_logs_action ON audit_logs(action);
CREATE INDEX idx_audit_logs_entity ON audit_logs(entity_type, entity_id);
CREATE INDEX idx_audit_logs_created ON audit_logs(created_at DESC);

-- ============================================
-- Triggers
-- ============================================

-- Auto-update updated_at
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_content_briefs_updated_at
    BEFORE UPDATE ON content_briefs
    FOR EACH ROW EXECUTE FUNCTION update_updated_at();

CREATE TRIGGER update_content_drafts_updated_at
    BEFORE UPDATE ON content_drafts
    FOR EACH ROW EXECUTE FUNCTION update_updated_at();

CREATE TRIGGER update_tasks_updated_at
    BEFORE UPDATE ON tasks
    FOR EACH ROW EXECUTE FUNCTION update_updated_at();

CREATE TRIGGER update_agents_updated_at
    BEFORE UPDATE ON agents
    FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- ============================================
-- Initial Data
-- ============================================

-- Insert default agents
INSERT INTO agents (id, name, role, tools, llm_model) VALUES
    ('agent-content-creator', 'ContentCreator', '内容研究创作者', '["hot_search", "trend_analysis", "style_reference", "viral_reference"]', 'claude-opus-4-20250514'),
    ('agent-content-reviewer', 'ContentReviewer', '内容审核员', '["quality_check", "brand_guidelines", "plagiarism_detector"]', 'claude-sonnet-4-20250514'),
    ('agent-platform-adapter', 'PlatformAdapter', '平台适配师', '["format_converter", "image_resizer", "hashtag_optimizer"]', 'claude-sonnet-4-20250514'),
    ('agent-platform-publisher', 'PlatformPublisher', '平台发布员', '["browser_automation", "api_publisher", "scheduler"]', 'claude-sonnet-4-20250514'),
    ('agent-data-analyst', 'DataAnalyst', '数据分析师', '["metrics_collector", "trend_analyzer", "report_generator"]', 'claude-sonnet-4-20250514')
ON CONFLICT (id) DO NOTHING;
