"""add workspace tables (client, account, hot_topic, metrics, task)

Revision ID: ab5431288062
Revises: 
Create Date: 2026-03-23 22:14:47.038995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab5431288062'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('industry', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('content_briefs',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('topic', sa.String(length=200), nullable=False),
    sa.Column('sub_topics', sa.JSON(), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.Column('target_audience', sa.JSON(), nullable=False),
    sa.Column('trending_topics', sa.JSON(), nullable=False),
    sa.Column('content_angle', sa.Text(), nullable=False),
    sa.Column('tone', sa.String(length=20), nullable=False),
    sa.Column('suggested_content_type', sa.String(length=20), nullable=False),
    sa.Column('primary_platform', sa.String(length=20), nullable=False),
    sa.Column('secondary_platforms', sa.JSON(), nullable=False),
    sa.Column('key_points', sa.JSON(), nullable=False),
    sa.Column('call_to_action', sa.Text(), nullable=False),
    sa.Column('hashtags', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('content_briefs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_briefs_topic'), ['topic'], unique=False)

    op.create_table('hot_topics',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('heat_score', sa.Float(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hot_topics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hot_topics_platform'), ['platform'], unique=False)

    op.create_table('tasks',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_task_type'), ['task_type'], unique=False)

    op.create_table('accounts',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('client_id', sa.String(length=20), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_logged_in', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content_drafts',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('brief_id', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=200), nullable=False),
    sa.Column('content_type', sa.String(length=20), nullable=False),
    sa.Column('platforms', sa.JSON(), nullable=False),
    sa.Column('platform_content', sa.JSON(), nullable=False),
    sa.Column('brand_voice', sa.String(length=100), nullable=False),
    sa.Column('tone', sa.String(length=20), nullable=False),
    sa.Column('reviews', sa.JSON(), nullable=False),
    sa.Column('current_score', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['brief_id'], ['content_briefs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('content_drafts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_drafts_status'), ['status'], unique=False)

    op.create_table('contents',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('draft_id', sa.String(length=50), nullable=True),
    sa.Column('topic', sa.String(length=200), nullable=False),
    sa.Column('content_type', sa.String(length=20), nullable=False),
    sa.Column('platforms', sa.JSON(), nullable=False),
    sa.Column('total_views', sa.Integer(), nullable=False),
    sa.Column('total_likes', sa.Integer(), nullable=False),
    sa.Column('total_comments', sa.Integer(), nullable=False),
    sa.Column('total_shares', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['content_drafts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contents_topic'), ['topic'], unique=False)

    op.create_table('metrics',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('content_id', sa.String(length=50), nullable=True),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('post_url', sa.String(length=500), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Integer(), nullable=True),
    sa.Column('shares', sa.Integer(), nullable=True),
    sa.Column('engagement_rate', sa.Float(), nullable=True),
    sa.Column('raw_metrics', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['content_drafts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_metrics_platform'), ['platform'], unique=False)

    op.create_table('publish_logs',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('draft_id', sa.String(length=50), nullable=True),
    sa.Column('content_id', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('schedule_type', sa.String(length=20), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('platforms', sa.JSON(), nullable=False),
    sa.Column('successful_posts', sa.JSON(), nullable=False),
    sa.Column('failed_platforms', sa.JSON(), nullable=False),
    sa.Column('errors', sa.JSON(), nullable=False),
    sa.Column('retry_attempts', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('published_by', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['draft_id'], ['content_drafts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('publish_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_publish_logs_status'), ['status'], unique=False)

    op.create_table('analytics',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('content_id', sa.String(length=50), nullable=True),
    sa.Column('draft_id', sa.String(length=50), nullable=True),
    sa.Column('publish_log_id', sa.String(length=50), nullable=True),
    sa.Column('period', sa.String(length=10), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('platform_analytics', sa.JSON(), nullable=False),
    sa.Column('total_views', sa.Integer(), nullable=False),
    sa.Column('total_likes', sa.Integer(), nullable=False),
    sa.Column('total_comments', sa.Integer(), nullable=False),
    sa.Column('total_shares', sa.Integer(), nullable=False),
    sa.Column('avg_engagement_rate', sa.Float(), nullable=False),
    sa.Column('insights', sa.JSON(), nullable=False),
    sa.Column('top_insights', sa.JSON(), nullable=False),
    sa.Column('comparison', sa.JSON(), nullable=True),
    sa.Column('next_steps', sa.JSON(), nullable=False),
    sa.Column('follow_up_topics', sa.JSON(), nullable=False),
    sa.Column('report_type', sa.String(length=20), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['draft_id'], ['content_drafts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['publish_log_id'], ['publish_logs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('platform_posts',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('publish_log_id', sa.String(length=50), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('post_id', sa.String(length=100), nullable=False),
    sa.Column('post_url', sa.String(length=500), nullable=False),
    sa.Column('initial_views', sa.Integer(), nullable=False),
    sa.Column('initial_likes', sa.Integer(), nullable=False),
    sa.Column('initial_comments', sa.Integer(), nullable=False),
    sa.Column('initial_shares', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['publish_log_id'], ['publish_logs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('platform_posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_platform_posts_platform'), ['platform'], unique=False)

    op.create_table('audience_insights',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('analytics_id', sa.String(length=50), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('age_groups', sa.JSON(), nullable=False),
    sa.Column('genders', sa.JSON(), nullable=False),
    sa.Column('locations', sa.JSON(), nullable=False),
    sa.Column('interests', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['analytics_id'], ['analytics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metric_snapshots',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('analytics_id', sa.String(length=50), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('post_id', sa.String(length=100), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Integer(), nullable=False),
    sa.Column('shares', sa.Integer(), nullable=False),
    sa.Column('saves', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['analytics_id'], ['analytics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('metric_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_metric_snapshots_recorded_at'), ['recorded_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('metric_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_metric_snapshots_recorded_at'))

    op.drop_table('metric_snapshots')
    op.drop_table('audience_insights')
    with op.batch_alter_table('platform_posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_platform_posts_platform'))

    op.drop_table('platform_posts')
    op.drop_table('analytics')
    with op.batch_alter_table('publish_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_publish_logs_status'))

    op.drop_table('publish_logs')
    with op.batch_alter_table('metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_metrics_platform'))

    op.drop_table('metrics')
    with op.batch_alter_table('contents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contents_topic'))

    op.drop_table('contents')
    with op.batch_alter_table('content_drafts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_drafts_status'))

    op.drop_table('content_drafts')
    op.drop_table('accounts')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_task_type'))
        batch_op.drop_index(batch_op.f('ix_tasks_status'))

    op.drop_table('tasks')
    with op.batch_alter_table('hot_topics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hot_topics_platform'))

    op.drop_table('hot_topics')
    with op.batch_alter_table('content_briefs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_briefs_topic'))

    op.drop_table('content_briefs')
    op.drop_table('clients')
    # ### end Alembic commands ###
