"""Content draft schema for generated content."""

from datetime import datetime
from enum import Enum
from typing import Any, Literal

from pydantic import BaseModel, Field, field_validator, model_validator

from src.schemas.content_brief import ContentType, PlatformType


class DraftStatus(str, Enum):
    """Draft status workflow."""

    DRAFT = "draft"
    IN_REVIEW = "in_review"
    APPROVED = "approved"
    REJECTED = "rejected"
    SCHEDULED = "scheduled"
    PUBLISHED = "published"


class QualityScore(BaseModel):
    """Content quality assessment scores."""

    relevance: float = Field(..., ge=0.0, le=10.0, description="Relevance to topic")
    readability: float = Field(..., ge=0.0, le=10.0, description="Readability score")
    engagement_potential: float = Field(
        ..., ge=0.0, le=10.0, description="Engagement potential"
    )
    brand_alignment: float = Field(..., ge=0.0, le=10.0, description="Brand voice alignment")
    platform_fit: float = Field(..., ge=0.0, le=10.0, description="Platform-specific fit")

    @property
    def overall(self) -> float:
        """Calculate overall quality score."""
        return round(
            (
                self.relevance * 0.25
                + self.readability * 0.2
                + self.engagement_potential * 0.25
                + self.brand_alignment * 0.15
                + self.platform_fit * 0.15
            ),
            1,
        )

    def passes_threshold(self, threshold: float = 7.0) -> bool:
        """Check if score passes quality threshold."""
        return self.overall >= threshold


class ContentBlock(BaseModel):
    """A content block for multi-format content."""

    type: Literal["text", "image", "video", "code", "quote", "list", "heading"] = Field(
        ..., description="Block type"
    )
    content: str = Field(..., description="Block content")
    metadata: dict[str, Any] = Field(default_factory=dict, description="Additional metadata")

    @field_validator("content")
    @classmethod
    def validate_content(cls, v: str, _info: Any) -> str:
        """Validate content based on block type."""
        if not v.strip():
            raise ValueError("Content cannot be empty")
        return v


class ReviewFeedback(BaseModel):
    """Review feedback for content."""

    reviewer: str = Field(default="system", description="Reviewer identifier")
    timestamp: datetime = Field(default_factory=datetime.now)
    approved: bool = Field(..., description="Whether content is approved")
    score: QualityScore = Field(..., description="Quality scores")
    issues: list[str] = Field(default_factory=list, description="Issues found")
    suggestions: list[str] = Field(default_factory=list, description="Improvement suggestions")
    comment: str = Field(default="", description="General comment")


class PlatformContent(BaseModel):
    """Platform-specific content variant."""

    platform: PlatformType = Field(..., description="Target platform")
    title: str = Field(..., min_length=1, max_length=100, description="Content title")
    content_blocks: list[ContentBlock] = Field(
        default_factory=list, description="Content blocks"
    )
    plain_text: str = Field(default="", description="Plain text version")
    character_count: int = Field(default=0, description="Character count")

    # Platform-specific fields
    hashtags: list[str] = Field(default_factory=list, description="Hashtags")
    mentions: list[str] = Field(default_factory=list, description="@mentions")
    cover_image_url: str | None = Field(default=None, description="Cover image URL")
    media_urls: list[str] = Field(default_factory=list, description="Media attachment URLs")

    # Metadata
    optimal_publish_time: str | None = Field(
        default=None, description="Suggested publish time (HH:MM)"
    )

    @model_validator(mode="after")
    def calculate_character_count(self) -> "PlatformContent":
        """Auto-calculate character count."""
        if self.plain_text:
            # Count actual characters, not bytes
            self.character_count = len(self.plain_text)
        else:
            self.character_count = sum(len(b.content) for b in self.content_blocks)
        return self

    def get_character_limit(self) -> int:
        """Get platform character limit."""
        limits = {
            PlatformType.XIAOHONGSHU: 1000,
            PlatformType.WECHAT: 20000,
            PlatformType.WEIBO: 2000,
            PlatformType.ZHIHU: 50000,
            PlatformType.DOUYIN: 2200,
            PlatformType.BILIBILI: 2000,
        }
        return limits.get(self.platform, 10000)

    def is_within_limit(self) -> bool:
        """Check if content is within character limit."""
        return self.character_count <= self.get_character_limit()


class ContentDraft(BaseModel):
    """Content draft generated by content crew."""

    # Metadata
    id: str = Field(..., description="Unique draft identifier")
    brief_id: str = Field(..., description="Reference to content brief")
    created_at: datetime = Field(default_factory=datetime.now)
    updated_at: datetime = Field(default_factory=datetime.now)
    version: int = Field(default=1, ge=1, description="Draft version number")

    # Status
    status: DraftStatus = Field(default=DraftStatus.DRAFT, description="Current status")

    # Content
    topic: str = Field(..., description="Main topic")
    content_type: ContentType = Field(default=ContentType.ARTICLE, description="Content type")
    platforms: list[PlatformType] = Field(
        ..., min_length=1, description="Target platforms"
    )
    platform_content: list[PlatformContent] = Field(
        default_factory=list, description="Platform-specific content"
    )

    # Branding
    brand_voice: str = Field(default="", description="Brand voice guidelines applied")
    tone: Literal["professional", "casual", "humorous", "inspiring", "educational"] = Field(
        default="professional"
    )

    # Review
    reviews: list[ReviewFeedback] = Field(default_factory=list, description="Review history")
    current_score: QualityScore | None = Field(default=None, description="Latest quality score")

    # Tags
    tags: list[str] = Field(default_factory=list, description="Content tags")
    category: str = Field(default="", description="Content category")

    @model_validator(mode="after")
    def update_timestamp(self) -> "ContentDraft":
        """Update timestamp on modification."""
        self.updated_at = datetime.now()
        return self

    def get_platform_content(self, platform: PlatformType) -> PlatformContent | None:
        """Get content for specific platform."""
        for pc in self.platform_content:
            if pc.platform == platform:
                return pc
        return None

    def get_latest_review(self) -> ReviewFeedback | None:
        """Get most recent review."""
        return self.reviews[-1] if self.reviews else None

    def is_approved(self) -> bool:
        """Check if draft is approved for all platforms."""
        return self.status == DraftStatus.APPROVED

    model_config = {"json_schema_extra": {"example": {}}}


# Example for documentation
ContentDraft.model_config["json_schema_extra"]["example"] = {
    "id": "draft-20250320-001",
    "brief_id": "brief-20250320-001",
    "version": 2,
    "status": "approved",
    "topic": "AI创业实战指南",
    "content_type": "article",
    "platforms": ["xiaohongshu", "wechat"],
    "platform_content": [
        {
            "platform": "xiaohongshu",
            "title": "AI创业3年，我踩过的5个坑",
            "plain_text": "作为连续创业者，我想分享...",
            "hashtags": ["#AI创业", "#创业干货"],
            "character_count": 850,
        }
    ],
    "brand_voice": "专业但不失亲和",
    "tone": "professional",
    "current_score": {
        "relevance": 9.0,
        "readability": 8.5,
        "engagement_potential": 8.0,
        "brand_alignment": 9.0,
        "platform_fit": 8.5,
    },
    "tags": ["AI", "创业", "经验分享"],
    "category": "创业经验",
}
