"""Core module exports."""

from src.core.audit import (
    AuditEvent,
    AuditEventType,
    AuditLogger,
    AuditSeverity,
    audit_log,
    get_audit_logger,
)
from src.core.auth import (
    APIKeyManager,
    AuthContext,
    CookieManager,
    EncryptionManager,
    JWTManager,
    TokenPayload,
    User,
    UserRole,
    require_auth,
)
from src.core.config import Settings, get_settings, settings
from src.core.error_handling import (
    CircuitBreaker,
    Error,
    ErrorContext,
    Result,
    Success,
    error,
    fallback,
    from_exception,
    jitter,
    retry_on_llm_error,
    retry_on_transient,
    safe_execute,
    safe_execute_async,
    success,
)
from src.core.exceptions import (
    # AnalyticsAgent exceptions
    AnalyticsException,
    AuthenticationError,
    BrowserCrashError,
    CaptchaRequiredError,
    ComplianceError,
    # ContentAgent exceptions
    ContentException,
    ContentNotFoundError,
    ContentRejectedError,
    CookieExpiredError,
    CrewException,
    # Database exceptions
    DatabaseException,
    DataFormatError,
    DeadlockError,
    DiskFullError,
    ElementNotFoundError,
    EmptyContentError,
    ForbiddenError,
    # HotspotAgent exceptions
    HotspotException,
    ImageComplianceError,
    ImageGenTimeoutError,
    IntegrityError,
    JSONDecodeError,
    LLMFormatError,
    LLMTimeoutError,
    NetworkTimeoutError,
    PoolExhaustedError,
    # PublishAgent exceptions
    PublishException,
    PublishRateLimitError,
    RateLimitError,
    TimeoutError,
    TokenLimitError,
)
from src.core.logging import logger, setup_logging

__all__ = [
    "APIKeyManager",
    "AnalyticsException",
    "AuditEvent",
    "AuditEventType",
    # Audit
    "AuditLogger",
    "AuditSeverity",
    "AuthContext",
    "AuthenticationError",
    "BrowserCrashError",
    "CaptchaRequiredError",
    "CircuitBreaker",
    "ComplianceError",
    "ContentException",
    "ContentNotFoundError",
    "ContentRejectedError",
    "CookieExpiredError",
    "CookieManager",
    # Exceptions
    "CrewException",
    "DataFormatError",
    "DatabaseException",
    "DeadlockError",
    "DiskFullError",
    "ElementNotFoundError",
    "EmptyContentError",
    "EncryptionManager",
    "Error",
    "ErrorContext",
    "ForbiddenError",
    "HotspotException",
    "ImageComplianceError",
    "ImageGenTimeoutError",
    "IntegrityError",
    "JSONDecodeError",
    "JWTManager",
    "LLMFormatError",
    "LLMTimeoutError",
    "NetworkTimeoutError",
    "PoolExhaustedError",
    "PublishException",
    "PublishRateLimitError",
    "RateLimitError",
    # Error handling
    "Result",
    # Config
    "Settings",
    "Success",
    "TimeoutError",
    "TokenLimitError",
    "TokenPayload",
    # Auth
    "User",
    "UserRole",
    "audit_log",
    "error",
    "fallback",
    "from_exception",
    "get_audit_logger",
    "get_settings",
    "jitter",
    # Logging
    "logger",
    "require_auth",
    "retry_on_llm_error",
    "retry_on_transient",
    "safe_execute",
    "safe_execute_async",
    "settings",
    "setup_logging",
    "success",
]
