"""Content database models."""

from datetime import datetime
from typing import TYPE_CHECKING
from uuid import uuid4

from sqlalchemy import JSON, DateTime, ForeignKey, Integer, String, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship

from src.models.base import Base, TimestampMixin

if TYPE_CHECKING:
    from src.models.analytics import Analytics
    from src.models.publish_log import PublishLog


class ContentType(str):
    """Content types."""

    ARTICLE = "article"
    VIDEO = "video"
    IMAGE = "image"
    THREAD = "thread"
    MIXED = "mixed"


class DraftStatus(str):
    """Draft status workflow."""

    DRAFT = "draft"
    IN_REVIEW = "in_review"
    APPROVED = "approved"
    REJECTED = "rejected"
    SCHEDULED = "scheduled"
    PUBLISHED = "published"


class ContentBrief(Base, TimestampMixin):
    """Content brief from topic research."""

    __tablename__ = "content_briefs"

    # Primary key
    id: Mapped[str] = mapped_column(
        String(50), primary_key=True, default=lambda: f"brief-{uuid4().hex[:12]}"
    )

    # Topic
    topic: Mapped[str] = mapped_column(String(200), nullable=False, index=True)
    sub_topics: Mapped[dict | None] = mapped_column(JSON, default=None)
    keywords: Mapped[dict] = mapped_column(JSON, nullable=False)  # List[str]

    # Audience analysis
    target_audience: Mapped[dict] = mapped_column(JSON, nullable=False)
    trending_topics: Mapped[dict] = mapped_column(JSON, nullable=False)

    # Content direction
    content_angle: Mapped[str] = mapped_column(Text, nullable=False)
    tone: Mapped[str] = mapped_column(String(20), nullable=False, default="professional")
    suggested_content_type: Mapped[str] = mapped_column(String(20), nullable=False)

    # Platform strategy
    primary_platform: Mapped[str] = mapped_column(String(20), nullable=False)
    secondary_platforms: Mapped[dict] = mapped_column(JSON, nullable=False)

    # Guidance
    key_points: Mapped[dict] = mapped_column(JSON, nullable=False)
    call_to_action: Mapped[str] = mapped_column(Text, default="")
    hashtags: Mapped[dict] = mapped_column(JSON, nullable=False)

    # Relationships
    drafts: Mapped[list["ContentDraft"]] = relationship(
        "ContentDraft", back_populates="brief", cascade="all, delete-orphan"
    )


class ContentDraft(Base, TimestampMixin):
    """Content draft generated by content crew."""

    __tablename__ = "content_drafts"

    # Primary key
    id: Mapped[str] = mapped_column(
        String(50), primary_key=True, default=lambda: f"draft-{uuid4().hex[:12]}"
    )

    # Foreign keys
    brief_id: Mapped[str] = mapped_column(
        String(50), ForeignKey("content_briefs.id", ondelete="CASCADE"), nullable=False
    )

    # Status
    status: Mapped[str] = mapped_column(
        String(20), nullable=False, default=DraftStatus.DRAFT, index=True
    )
    version: Mapped[int] = mapped_column(Integer, nullable=False, default=1)

    # Content
    topic: Mapped[str] = mapped_column(String(200), nullable=False)
    content_type: Mapped[str] = mapped_column(String(20), nullable=False)
    platforms: Mapped[dict] = mapped_column(JSON, nullable=False)  # List[str]
    platform_content: Mapped[dict] = mapped_column(JSON, nullable=False)  # List[PlatformContent]

    # Branding
    brand_voice: Mapped[str] = mapped_column(String(100), default="")
    tone: Mapped[str] = mapped_column(String(20), nullable=False, default="professional")

    # Review
    reviews: Mapped[dict] = mapped_column(JSON, nullable=False)  # List[ReviewFeedback]
    current_score: Mapped[dict | None] = mapped_column(JSON, default=None)  # QualityScore

    # Tags
    tags: Mapped[dict] = mapped_column(JSON, nullable=False)  # List[str]
    category: Mapped[str] = mapped_column(String(50), default="")

    # Relationships
    brief: Mapped["ContentBrief"] = relationship("ContentBrief", back_populates="drafts")
    publish_logs: Mapped[list["PublishLog"]] = relationship(
        "PublishLog", back_populates="draft", cascade="all, delete-orphan"
    )
    analytics: Mapped[list["Analytics"]] = relationship(
        "Analytics", back_populates="draft", cascade="all, delete-orphan"
    )

    @property
    def is_approved(self) -> bool:
        """Check if draft is approved."""
        return self.status == DraftStatus.APPROVED


class Content(Base, TimestampMixin):
    """Published content record."""

    __tablename__ = "contents"

    # Primary key
    id: Mapped[str] = mapped_column(
        String(50), primary_key=True, default=lambda: f"content-{uuid4().hex[:12]}"
    )

    # Foreign keys
    draft_id: Mapped[str | None] = mapped_column(
        String(50), ForeignKey("content_drafts.id", ondelete="SET NULL"), nullable=True
    )

    # User ownership
    user_id: Mapped[str] = mapped_column(String(50), nullable=False, index=True)

    # Content info
    topic: Mapped[str] = mapped_column(String(200), nullable=False, index=True)
    title: Mapped[str] = mapped_column(String(200), nullable=False, default="")
    body: Mapped[str] = mapped_column(Text, nullable=False, default="")
    content_type: Mapped[str] = mapped_column(String(20), nullable=False, default="article")
    platforms: Mapped[dict] = mapped_column(JSON, nullable=False)

    # Media
    images: Mapped[dict] = mapped_column(JSON, nullable=False, default=list)
    video_url: Mapped[str | None] = mapped_column(String(500), nullable=True, default=None)

    # Tags & metadata
    hashtags: Mapped[dict] = mapped_column(JSON, nullable=False, default=list)
    extra_metadata: Mapped[dict | None] = mapped_column("metadata", JSON, nullable=True, default=None)

    # Status
    status: Mapped[str] = mapped_column(
        String(20), nullable=False, default="draft", index=True
    )

    # Performance tracking
    total_views: Mapped[int] = mapped_column(Integer, default=0)
    total_likes: Mapped[int] = mapped_column(Integer, default=0)
    total_comments: Mapped[int] = mapped_column(Integer, default=0)
    total_shares: Mapped[int] = mapped_column(Integer, default=0)

    # Metadata
    published_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), default=None)
    last_synced_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), default=None)

    # Relationships
    draft: Mapped["ContentDraft"] = relationship("ContentDraft")
    analytics: Mapped[list["Analytics"]] = relationship(
        "Analytics", back_populates="content", cascade="all, delete-orphan"
    )
    publish_logs: Mapped[list["PublishLog"]] = relationship(
        "PublishLog", back_populates="content", cascade="all, delete-orphan"
    )
